Repository RedHatInsights/compliance-frontend, pull requests merged in 2024-10, with the labels that each got.

#2148 feat(RHINENG-11719): migrate report download modal to REST api
  package-lock.json
  src/PresentationalComponents/GatedComponents.js
  src/SmartComponents/CompliancePolicies/CompliancePolicies.js
  src/SmartComponents/CreatePolicy/EditPolicySystems.js
  src/SmartComponents/ReportDetails/ReportDetails.js
  src/SmartComponents/ReportDetails/constants.js
  src/SmartComponents/ReportDownload/ReportDownload.js
  src/SmartComponents/ReportDownload/hooks/apiQueryHooks.js
  src/SmartComponents/ReportDownload/hooks/helpers.js
  src/SmartComponents/ReportDownload/hooks/useExportSettings.js
  src/SmartComponents/ReportDownload/hooks/usePDFExport.js
  src/SmartComponents/ReportDownload/hooks/usePDFExport.test.js
  src/SmartComponents/ReportDownload/hooks/useQueryExportData.js
  src/SmartComponents/ReportDownload/hooks/useQueryExportData.test.js
  src/SmartComponents/Reports/Reports.js
  src/SmartComponents/Reports/constants.js
  src/Utilities/helpers.js
  src/Utilities/hooks/useQuery/apiInstance.js
  src/__factories__/helpers.js
  src/__factories__/systemsRest.js
  src/__factories__/testResults.js
  src/constants.js
Labels: enhancement

#2151 feat(RHINENG-10394): Migrate System Detail page to REST API
  src/PresentationalComponents/SystemPolicyCard/SystemPolicyCard.js
  src/PresentationalComponents/SystemPolicyCards/SystemPolicyCards.js
  src/PresentationalComponents/SystemPolicyCards/components/LoadingPolicyCards.js
  src/SmartComponents/SystemDetails/ComplianceDetail.js
  src/SmartComponents/SystemDetails/SystemDetails.js
  src/SmartComponents/SystemDetails/SystemDetails.test.js
  src/SmartComponents/SystemPolicyCards/SystemPolicyCards.js
  src/SmartComponents/SystemPolicyCards/SystemPolicyCards.test.js
  src/SmartComponents/SystemPolicyCards/constants.js
  src/Utilities/hooks/api/useReportTestResults.js
  src/Utilities/hooks/api/useSystem.js
  src/Utilities/hooks/api/useSystemPolicies.js
  src/Utilities/hooks/api/useSystemReports.js
  src/Utilities/hooks/useQuery/apiInstance.js
  src/__factories__/systemReports.js
  src/__factories__/testResults.js
Labels: enhancement

#2176 feat(RHINENG-12789): Migrate the first step of Create policy wizard
  config/setupTests.js
  src/AppEntry.js
  src/DevAppEntry.js
  src/SmartComponents/ComplianceSystems/ComplianceSystems.js
  src/SmartComponents/CreatePolicy/Components/PolicyTypeTable.js
  src/SmartComponents/CreatePolicy/CreateSCAPPolicy.js
  src/SmartComponents/CreatePolicy/CreateSCAPPolicy/CreateSCAPPolicy.js
  src/SmartComponents/CreatePolicy/CreateSCAPPolicy/CreateSCAPPolicy.test.js
  src/SmartComponents/CreatePolicy/CreateSCAPPolicy/CreateSCAPPolicyBase.js
  src/SmartComponents/CreatePolicy/CreateSCAPPolicy/CreateSCAPPolicyGraphQL.js
  src/SmartComponents/CreatePolicy/CreateSCAPPolicy/CreateSCAPPolicyRest.js
  src/SmartComponents/CreatePolicy/CreateSCAPPolicy/CreateSCAPPolicyRest.test.js
  src/SmartComponents/CreatePolicy/CreateSCAPPolicy/index.js
  src/Utilities/dataSerialiser.js
  src/Utilities/dataSerialiser.test.js
  src/Utilities/hooks/useQuery/apiInstance.js
  src/Utilities/hooks/useQuery/useQuery.js
  src/Utilities/hooks/useSecurityGuidesOS/useSecurityGuidesOS.js
  src/Utilities/hooks/useSupportedProfiles/useSupportedProfiles.js
  src/__fixtures__/supportedProfiles.js
  src/constants.js
  src/store/index.js
Labels: enhancement

#2203 fix(CreateSCAPPolicyGraphQL): Return the "In use" label
  src/SmartComponents/CreatePolicy/CreateSCAPPolicy/CreateSCAPPolicyGraphQL.js
Labels: bug

#2201 fix(SystemsTable): Enable selection and refactor useSystemBulkSelect
  package-lock.json
  src/SmartComponents/SystemsTable/SystemsTableGraphQL.js
  src/SmartComponents/SystemsTable/SystemsTableRest.js
  src/SmartComponents/SystemsTable/hooks.js
  src/SmartComponents/SystemsTable/hooks/useLoadedItems.js
  src/SmartComponents/SystemsTable/hooks/useLoadedItems.test.js
  src/Utilities/unionBy.js
  src/Utilities/unionBy.test.js
Labels: bug

#2202 feat(CreatePolicy > EditPolicySystems): Support REST API requests
  src/SmartComponents/ComplianceSystems/ComplianceSystems.js
  src/SmartComponents/CreatePolicy/EditPolicySystems.js
Labels: enhancement, migration

#2200 fix(RHINENG-13403): apply tag filtering into REST
  package-lock.json
  package.json
  src/SmartComponents/ComplianceSystems/ComplianceSystems.js
  src/SmartComponents/PolicyDetails/PolicySystemsTab.js
  src/SmartComponents/SystemsTable/SystemsTableRest.js
  src/SmartComponents/SystemsTable/SystemsTableRest.test.js
  src/SmartComponents/SystemsTable/hooks.js
  src/SmartComponents/SystemsTable/hooks.test.js
  src/SmartComponents/SystemsTable/hooks/useFetchSystems.js
  src/SmartComponents/SystemsTable/hooks/useFetchSystems.test.js
  src/Utilities/hooks/api/useReports.js
Labels: migration

#2221 fix(ApiClient): use params correct order
  src/SmartComponents/PolicyDetails/PolicySystemsTab.js
  src/SmartComponents/ReportDownload/hooks/apiQueryHooks.js
  src/Utilities/hooks/api/useReportTestResults.js
  src/Utilities/hooks/useSupportedProfiles/useSupportedProfiles.js
Labels: bug

#2220 fix(RHINENG-13404): Fix preselected not working with useSystemBulkSelect
  src/SmartComponents/CreatePolicy/EditPolicySystems.js
  src/SmartComponents/EditPolicy/EditPolicySystemsTab.js
  src/SmartComponents/SystemsTable/hooks.js
  src/SmartComponents/SystemsTable/hooks/useLoadedItems.js
Labels: bug
