Repository RedHatInsights/compliance-frontend, pull requests merged in 2024-11, with the labels that each got.

#2236 fix(CompliancePolicies): Fix the policies page constant re-render
  src/SmartComponents/CompliancePolicies/CompliancePolicies.js
Labels: bug, migration

#2232 fix(RHINENG-13974): Adapt to 'IN' search backend
  src/PresentationalComponents/ComplianceTable/serialisers.js
  src/PresentationalComponents/ComplianceTable/serialisers.test.js
  src/PresentationalComponents/Tailorings/hooks/useTailoringsData.js
  src/SmartComponents/CreatePolicy/EditPolicySystems.js
  src/SmartComponents/SystemsTable/SystemsTableRest.test.js
  src/SmartComponents/SystemsTable/hooks/useFetchSystems.js
Labels: bug, migration

#2209 feat(RHINENG-12792): Migrate the Review (final) wizard step
  src/SmartComponents/CreatePolicy/CreateSCAPPolicy/CreateSCAPPolicyRest.js
  src/SmartComponents/CreatePolicy/CreateSCAPPolicy/CreateSCAPPolicyRest.test.js
  src/SmartComponents/CreatePolicy/FinishedCreatePolicy/FinishedCreatePolicy.js
  src/SmartComponents/CreatePolicy/FinishedCreatePolicy/FinishedCreatePolicy.test.js
  src/SmartComponents/CreatePolicy/FinishedCreatePolicy/FinishedCreatePolicyBase.js
  src/SmartComponents/CreatePolicy/FinishedCreatePolicy/FinishedCreatePolicyGraphQL.js
  src/SmartComponents/CreatePolicy/FinishedCreatePolicy/FinishedCreatePolicyGraphQL.test.js
  src/SmartComponents/CreatePolicy/FinishedCreatePolicy/FinishedCreatePolicyRest.js
  src/SmartComponents/CreatePolicy/FinishedCreatePolicy/FinishedCreatePolicyRest.test.js
  src/SmartComponents/CreatePolicy/FinishedCreatePolicy/index.js
  src/Utilities/hooks/api/useAssignRules.js
  src/Utilities/hooks/api/useAssignSystems.js
  src/Utilities/hooks/api/useCreatePolicy.js
Labels: migration

#2243 fix(compileState): Make applyObservers work with any number of observers
  src/Frameworks/AsyncTableTools/hooks/usePagination/usePagination.js
  src/Frameworks/AsyncTableTools/hooks/useTableState/helpers/compileState.js
  src/Frameworks/AsyncTableTools/hooks/useTableState/helpers/compileState.test.js
  src/Frameworks/AsyncTableTools/hooks/useTableState/useTableState.js
Labels: bug, migration

#2244 fix(RHINENG-14124): Make some queries work again v2
  src/SmartComponents/CompliancePolicies/CompliancePolicies.js
  src/SmartComponents/SystemPolicyCards/SystemPolicyCards.js
  src/SmartComponents/SystemPolicyCards/SystemPolicyCards.test.js
Labels: bug, migration, approved

#2247 fix(RHINENG-14247): Use correct api sort by parameter on Systems
  src/SmartComponents/ComplianceSystems/ComplianceSystems.js
  src/SmartComponents/CreatePolicy/EditPolicySystems.js
  src/SmartComponents/EditPolicy/EditPolicySystemsTab.js
  src/SmartComponents/PolicyDetails/PolicySystemsTab.js
  src/SmartComponents/SystemsTable/Columns.js
Labels: migration

#2234 feat(RHINENG-11549): Report detail - System Table migration
  src/PresentationalComponents/ComplianceRemediationButton/RemediationButtonRest.js
  src/PresentationalComponents/ComplianceRemediationButton/hooks.js
  src/SmartComponents/ReportDetails/Components/TabTitleWithData.js
  src/SmartComponents/ReportDetails/Components/hooks/useFetchNeverReported.js
  src/SmartComponents/ReportDetails/Components/hooks/useFetchReporting.js
  src/SmartComponents/ReportDetails/ReportDetails.js
  src/SmartComponents/ReportDetails/constants.js
  src/SmartComponents/SystemsTable/Cells.js
  src/SmartComponents/SystemsTable/Columns.js
  src/SmartComponents/SystemsTable/SystemsTableRest.js
  src/constants.js
Labels: enhancement, migration

#2260 fix(RulesTable): selection is fixed
  src/Frameworks/AsyncTableTools/hooks/useAsyncTableTools/useAsyncTableTools.js
  src/Frameworks/AsyncTableTools/hooks/useBulkSelect/useBulkSelect.js
  src/Frameworks/AsyncTableTools/hooks/useSelectionManager/useSelectionManager.js
  src/PresentationalComponents/RulesTable/RulesTableRest.js
  src/PresentationalComponents/Tailorings/Tailorings.js
  src/PresentationalComponents/Tailorings/components/TailoringTab.js
Labels: bug, migration

#2233 feat(PolicyDetails): RHINENG-11701 - Use tailorings rule tree
  package-lock.json
  package.json
  src/Frameworks/AsyncTableTools/hooks/useExpandable/useExpandable.js
  src/Frameworks/AsyncTableTools/hooks/useTableSort/helpers.js
  src/Frameworks/AsyncTableTools/hooks/useTableSort/useTableSort.js
  src/Frameworks/AsyncTableTools/hooks/useTableView/hooks/useViewState.js
  src/Frameworks/AsyncTableTools/hooks/useTableView/views/treeChopper.js
  src/PresentationalComponents/RulesTable/Filters.js
  src/PresentationalComponents/RulesTable/RulesTableRest.js
  src/PresentationalComponents/Tailorings/Tailorings.js
  src/PresentationalComponents/Tailorings/components/TabHeader.js
  src/PresentationalComponents/Tailorings/components/TailoringTab.js
  src/PresentationalComponents/Tailorings/helpers.js
  src/PresentationalComponents/Tailorings/hooks/useBatchedRuleGroups.js
  src/PresentationalComponents/Tailorings/hooks/useBatchedValueDefinitions.js
  src/PresentationalComponents/Tailorings/hooks/useSecurityGuideData.js
  src/PresentationalComponents/Tailorings/hooks/useTailoringsData.js
  src/Utilities/hooks/api/useRules.js
  src/Utilities/hooks/api/useSecurityGuide.js
  src/Utilities/hooks/api/useSecurityGuideProfiles.js
  src/Utilities/hooks/api/useSecurityGuides.js
  src/Utilities/hooks/api/useTailoringRuleTree.js
Labels: enhancement, migration

#2252 feat(RHINENG-13595): Migrate the rules table on the system details page
  src/Frameworks/AsyncTableTools/hooks/useTableState/helpers/compileState.js
  src/Frameworks/AsyncTableTools/hooks/useTableState/helpers/compileState.test.js
  src/Modules/ComplianceDetails.js
  src/PresentationalComponents/ComplianceTable/serialisers.js
  src/PresentationalComponents/RulesTable/Filters.js
  src/PresentationalComponents/RulesTable/RulesTable.js
  src/PresentationalComponents/RulesTable/RulesTableRest.js
  src/SmartComponents/SystemDetails/Cells.js
  src/SmartComponents/SystemDetails/Columns.js
  src/SmartComponents/SystemDetails/Details.js
  src/SmartComponents/SystemDetails/RuleResults.js
  src/SmartComponents/SystemDetails/SystemDetails.js
  src/SmartComponents/SystemDetails/SystemPoliciesAndRules.js
  src/SmartComponents/SystemDetails/SystemPoliciesAndRulesRest.js
  src/SmartComponents/SystemDetails/constants.js
  src/SmartComponents/SystemDetails/useTestResults.js
  src/SmartComponents/SystemPolicyCards/SystemPolicyCards.js
  src/SmartComponents/SystemPolicyCards/SystemPolicyCards.test.js
  src/Utilities/hooks/api/useReportRuleResults.js
  src/__factories__/testResults.js
Labels: migration

#2272 fix(RHINENG-14376): filter systems correctly on Wizard
  src/SmartComponents/CreatePolicy/EditPolicySystems.js
Labels: migration

#2273 fix(RHINENG-14374): Put filter name in double quotes
  src/Frameworks/AsyncTableTools/__fixtures__/filters.js
  src/SmartComponents/SystemsTable/SystemsTableRest.test.js
  src/SmartComponents/SystemsTable/constants.js
  src/constants.js
Labels: migration

#2274 feat(RHINENG-14388): Make reports percent compliant filter work
  package-lock.json
  package.json
  src/PresentationalComponents/ReportsTable/Filters.js
  src/SmartComponents/ReportDetails/Components/hooks/useFetchReporting.js
  src/SmartComponents/ReportDownload/hooks/apiQueryHooks.js
Labels: migration

#2253 feat(RHINENG-14272): Policies page - async table
  src/Frameworks/AsyncTableTools/components/AsyncTableToolsTable/AsyncTableToolsTable.js
  src/Frameworks/AsyncTableTools/hooks/useAsyncTableTools/useAsyncTableTools.js
  src/Frameworks/AsyncTableTools/hooks/useExporter/index.js
  src/Frameworks/AsyncTableTools/hooks/useExporter/useExporter.js
  src/PresentationalComponents/LoadingPoliciesTable/LoadingPoliciesTable.js
  src/PresentationalComponents/LoadingPoliciesTable/LoadingPoliciesTable.test.js
  src/PresentationalComponents/PoliciesTable/Columns.js
  src/PresentationalComponents/PoliciesTable/Filters.js
  src/PresentationalComponents/PoliciesTable/PoliciesTable.js
  src/SmartComponents/CompliancePolicies/CompliancePolicies.cy.js
  src/SmartComponents/CompliancePolicies/CompliancePolicies.js
  src/SmartComponents/CompliancePolicies/CompliancePolicies.test.js
  src/SmartComponents/CompliancePolicies/CompliancePoliciesGraphQL.js
  src/SmartComponents/CompliancePolicies/CompliancePoliciesRest.js
  src/SmartComponents/CompliancePolicies/components/CreateLink.js
  src/SmartComponents/Reports/Reports.js
  src/Utilities/hooks/usePoliciesCount.js
Labels: migration

#2277 fix(RHINENG-14373): make patching value work
  src/SmartComponents/PolicyDetails/hooks/useSaveValueOverrides.js
Labels: bug, migration

#2276 fix(RHINENG-14371): fix tabs ordering and 0 value
  src/PresentationalComponents/TabbedRules/OsVersionText.js
  src/PresentationalComponents/Tailorings/Tailorings.js
Labels: bug, migration

#2275 feat(RHINENG-14389): Add SSG filter report details page
  src/SmartComponents/ReportDetails/ReportDetails.js
  src/SmartComponents/SystemsTable/SystemsTableRest.js
  src/Utilities/hooks/api/useReportTestResultsSG.js
Labels: migration

#2278 feat(RHINENG-14288): Show table loading on sort&filter actions
  src/PresentationalComponents/ReportsTable/ReportsTable.js
  src/SmartComponents/Reports/Reports.js
Labels: bug, migration

#2214 feat(RHINENG-13052): Migrate PolicyRules Page to v2
  .gitignore
  src/Frameworks/AsyncTableTools/hooks/useTableView/views/treeChopper.js
  src/PresentationalComponents/RulesTable/helpers.js
  src/PresentationalComponents/Tailorings/components/TabHeader.js
  src/PresentationalComponents/Tailorings/hooks/useSecurityGuideData.js
  src/PresentationalComponents/hooks/useBatchedRuleGroups.js
  src/Routes.js
  src/SmartComponents/PolicyRules/PolicyRules.js
  src/SmartComponents/PolicyRules/PolicyRulesHeader.js
  src/SmartComponents/PolicyRules/helpers.js
  src/SmartComponents/PolicyRules/usePolicyRules.test.js
  src/Utilities/hooks/api/usePolicyRulesList.js
  src/Utilities/hooks/api/useProfileRules.js
  src/Utilities/hooks/api/useProfileTree.js
Labels: migration

#2280 fix: Fix another params order issue un useReportTestResults
  src/SmartComponents/SystemDetails/useTestResults.js
Labels: bug

#2279 Fix dataMap for Policies table
  src/SmartComponents/CompliancePolicies/constants.js
Labels: bug, migration

#2284 feat(RHINENG-14417): system detail default filter
  src/PresentationalComponents/RulesTable/RulesTableRest.js
  src/SmartComponents/SystemDetails/RuleResults.js
Labels: migration

#2281 fix(RHINENG-14285): filter chips removal
  src/Frameworks/AsyncTableTools/hooks/useSelectionManager/reducer.js
Labels: migration

#2265 feat(RHINENG-14339): Unite asynctables & v2 FF
  src/PresentationalComponents/ComplianceTable/ComplianceTable.js
  src/PresentationalComponents/ComplianceTable/ComplianceTable.test.js
  src/PresentationalComponents/PoliciesTable/PoliciesTable.test.js
  src/SmartComponents/CreatePolicy/CreateSCAPPolicy/CreateSCAPPolicyRest.js
  src/constants.js
Labels: migration

#2290 fix: Temporarily hide the Edit policy feature/buttons
  src/PresentationalComponents/PoliciesTable/hooks/useActionResolvers.js
  src/SmartComponents/PolicyDetails/EditRulesButtonToolbarItem.js
  src/SmartComponents/PolicyDetails/EditSystemsButtonToolbarItem.js
Labels: migration

#2293 fix(EditPolicy): Fix selection for multiple security guides scenario
  src/SmartComponents/CreatePolicy/EditPolicyProfilesRules/useProfileRuleIds.js
  src/SmartComponents/EditPolicy/EditPolicyRulesTabRest.js
Labels: bug, migration

#2295 fix(RHINENG-14132): PDF download GQL when BO is set
  src/SmartComponents/ReportDownload/Components/ReportPDF.js
  src/constants.js
Labels: bug, migration
