Repository RedHatInsights/compliance-frontend, pull requests merged in 2025-01, with the labels that each got.

#2319 fix(RulesTable): prevent error on rule expand
  src/PresentationalComponents/RulesTable/RulesTableRest.js
Labels: bug

#2321 fix(RHINENG-15165): sorting by name in Never reported table
  src/SmartComponents/ReportDetails/ReportDetails.js
Labels: bug

#2297 fix(RHINENG-10460): column sorting
  cypress/support/commands.js
  src/Frameworks/AsyncTableTools/hooks/useAsyncTableTools/useAsyncTableTools.js
  src/Frameworks/AsyncTableTools/hooks/useTableSort/helpers.js
  src/Frameworks/AsyncTableTools/hooks/useTableSort/useTableSort.js
  src/PresentationalComponents/ComplianceTable/ComplianceTable.js
  src/SmartComponents/CompliancePolicies/CompliancePolicies.cy.js
Labels: bug, migration

#2314 fix(Tailorings): RHINENG-14520 - Fix export for wizard
  src/Frameworks/AsyncTableTools/utils/withExport/withExport.js
  src/PresentationalComponents/Tailorings/components/TailoringTab.js
  src/Utilities/hooks/useFetchTotalBatched.js
Labels: bug

#2330 fix(Create/EditPolicy/PolicyDetails): Add missing system number badges
  src/PresentationalComponents/TabbedRules/OsVersionText.js
  src/PresentationalComponents/TabbedRules/ProfileTabContent.js
  src/PresentationalComponents/Tailorings/SystemCountBadge.js
  src/PresentationalComponents/Tailorings/Tailorings.js
  src/SmartComponents/CreatePolicy/EditPolicyProfilesRules/EditPolicyProfilesRulesRest.js
  src/SmartComponents/EditPolicy/EditPolicyFormRest.js
  src/SmartComponents/EditPolicy/EditPolicyRulesTabRest.js
  src/SmartComponents/PolicyDetails/PolicyDetails.js
  src/SmartComponents/PolicyDetails/PolicyDetails.test.js
  src/SmartComponents/PolicyDetails/PolicyMultiversionRules.js
  src/SmartComponents/PolicyDetails/PolicyMultiversionRules.test.js
  src/SmartComponents/ReportDetails/Components/hooks/useLegendData.js
  src/Utilities/TextHelper.js
  src/Utilities/hooks/api/usePolicyOsVersionCounts.js
  src/Utilities/hooks/api/usePolicySystems.js
  src/Utilities/hooks/api/usePolicySystemsOS.js
Labels: bug

#2312 fix(RHINENG-14893): Correct empty state SystemDetails
  src/SmartComponents/SystemDetails/Details.js
  src/SmartComponents/SystemDetails/EmptyState.js
  src/SmartComponents/SystemDetails/EmptyState.test.js
  src/SmartComponents/SystemDetails/NoReportsState.js
  src/SmartComponents/SystemDetails/NoReportsState.test.js
  src/SmartComponents/SystemDetails/SystemDetails.js
  src/SmartComponents/SystemDetails/SystemDetails.test.js
  src/SmartComponents/SystemDetails/SystemPoliciesAndRules.js
  src/SmartComponents/SystemDetails/SystemPoliciesAndRulesRest.js
Labels: bug, enhancement

#2306 feat(Tailorings): Implement group selection
  src/Frameworks/AsyncTableTools/hooks/useAsyncTableTools/useAsyncTableTools.js
  src/Frameworks/AsyncTableTools/hooks/useBulkSelect/__snapshots__/useBulkSelect.test.js.snap
  src/Frameworks/AsyncTableTools/hooks/useBulkSelect/useBulkSelect.js
  src/Frameworks/AsyncTableTools/hooks/useTableView/helpers.js
  src/Frameworks/AsyncTableTools/hooks/useTableView/views/index.js
  src/Frameworks/AsyncTableTools/hooks/useTableView/views/treeChopper.js
  src/PresentationalComponents/RulesTable/RulesTableRest.js
  src/PresentationalComponents/Tailorings/components/TailoringTab.js
  src/PresentationalComponents/Tailorings/helpers.js
  src/PresentationalComponents/Tailorings/helpers.test.js
  src/SmartComponents/CreatePolicy/EditPolicyProfilesRules/EditPolicyProfilesRulesRest.js
Labels: bug

#2354 feat(RHINENG-15537): Return back RuleResults export
  src/SmartComponents/SystemDetails/Columns.js
  src/SmartComponents/SystemDetails/RuleResults.js
  src/Utilities/hooks/api/useReportRuleResults.js
  src/Utilities/hooks/useQuery/useQuery.js
Labels: migration

#2355 fix(RHINENG-14893): Fix bug with OR and improve tests
  src/SmartComponents/SystemDetails/EmptyState.js
  src/SmartComponents/SystemDetails/EmptyState.test.js
Labels: bug
